apiVersion: apps/v1
kind: Deployment
metadata:
  name: moer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moer
  template:
    metadata:
      labels:
        app: moer
    spec:
      containers:
      - image: okteto.dev/moer:latest
        name: moer
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "beauty-upgrade.tw"
        - name: Vless_UUID
          value: "8353e4c9-24dc-4225-b819-4125ee1e5d38"
        - name: Vless_Path
          value: "/fhfhUTT"
        - name: Vmess_UUID
          value: "8353e4c9-24dc-4225-b819-4125ee1e5d38"
        - name: Vmess_Path
          value: "/d4b3grERT"
        - name: Share_Path
          value: "/share233"
